project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ui.urls')),
    
]

project/ui/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'ui'
urlpatterns = [
    # path('',views.home,name="home"),
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('output', views.output,name='output'),
    path('texttospeech',views.texttospeech,name='texttospeech'),
    path('translate-summary', views.translate_summary, name='translate_summary'),
    # path('correct_grammar',views.correct_grammar,name='correct_grammar'),
    path('grammar_checker',views.grammar_checker,name="grammar_checker"),
    path('registration/',views.registration,name='registration'),
    # path('registration/registration',views.registration,name='registration'),
    path('pdf1',views.pdf1,name='pdf1'),
    path('pdf_summary_view',views.pdf_summary_view,name="pdf_summary_view"),
    # path('pdf',views.pdf,name='pdf'),
    path('grammar',views.grammar,name='grammar'),
    path('profile',views.profile,name='profile'),
    path('history',views.history,name='history'),
    path('home',views.home,name="home"),
    path('summarease',views.summarease,name="summarease"),
    path('forgotpassword',views.forgotpassword,name='forgotpassword'),
    # path('login/summarease',views.summarease,name='summarease'),
    # path('forgotpassword/',views.forgotpassword,name='forgotpassword'),
    # path('login/summarease/home',views.home,name='home'),
    # path('registration/login',views.login,name='login'),
    # path('registration/summarease',views.summarease,name='summarease'),
    # path('registration/home',views.home,name='home'),
    # path('login/home',views.home,name="home"),
    # path('login/registration',views.registration,name ="registration"),
    # path('login/forgotpassword',views.forgotpassword,name='forgotpassword'),
    
]

project/ui/models.py
# # models.py
# from django.db import models
# from djongo import models as djongo_models

# class UserProfile(djongo_models.Model):
#     userName = models.CharField(max_length=255, unique=True)
#     email = djongo_models.EmailField(unique=True)
#     password = models.CharField(max_length=255)
# myapp/models.py

from django.db import models
# from django.contrib.auth.models import User

class Summary(models.Model):
    input_text = models.TextField()
    generated_summary = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class UploadedFile(models.Model):
    file_name = models.CharField(max_length=255)
    upload_date = models.DateTimeField(auto_now_add=True)

    # In pdf_summarizer/models.py

from django.db import models

class UploadedPDF(models.Model):
    pdf_file = models.FileField(upload_to='uploaded_pdfs/')

project/ui/forms.py
# from django import forms

# class PdfForm(forms.Form):
#     pdf_file = forms.FileField()
#     pages_to_summarize = forms.CharField(max_length=255)
# In pdf_summarizer/forms.py

# from django import forms
# from .models import UploadedPDF  # Assuming you have a model for uploaded PDFs

# class UploadPDFForm(forms.ModelForm):
#     class Meta:
#         model = UploadedPDF  # Assuming you have a model named UploadedPDF
#         fields = ['pdf_file']

project/ui/views.py
from django.shortcuts import redirect, render
from httpx import request
import requests
from googletrans import Translator
from transformers import PegasusForConditionalGeneration, PegasusTokenizer
from django.http import JsonResponse
from PyPDF2 import PdfReader
import requests
import pyttsx3
from googletrans import Translator


# from pymongo import MongoClient

from django.http import JsonResponse
from django.template.loader import render_to_string

# from project.ui.forms import UploadPDFForm

# In pdf_summarizer/views.py

import os
import PyPDF2
import nltk
from django.shortcuts import render
from django.http import JsonResponse
from transformers import pipeline
from django.conf import settings

import fitz 

# try:
#     nltk.data.find('tokenizers/punkt')
# except LookupError:
#     nltk.download('punkt')

def summarize_pdf(file_path):
    # pdf_reader = PyPDF2.PdfReader(file_path)
    # text = ""
    # for page_num in range(len(pdf_reader.pages)):
    #     page = pdf_reader.pages[page_num]
    #     text += page.extractText()
    text = ""

    # Open the PDF file
    pdf_document = fitz.open(file_path)

    # Iterate over pages and extract text
    for page_num in range(pdf_document.page_count):
        page = pdf_document[page_num]
        text += page.get_text()

    # Close the PDF file
    pdf_document.close()
    sentences = nltk.sent_tokenize(text)

    # summarizer = pipeline("summarization")
    # summary = summarizer(sentences, max_length=100, min_length=50, do_sample=False)[0]

    # return summary['summary_text']
    document = " ".join(sentences)
    text = summarizer(document, max_length=130,min_length=60,do_sample=False)[0]['summary_text']

    return text
    # api_url = "https://api-inference.huggingface.co/models/facebook/bart-large-cnn"
    
    # api_headers = {
    #     "Authorization": "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",  # Replace with your actual API token
    #     "Content-Type": "application/json"
    # }

    # # Set up the data payload
    # data = {
    #     "inputs": document,
    #     "options": {
    #         "max_length": 100,
    #         "min_length": 50,
    #         "do_sample": False
    #     }
    # }
    # response = requests.post(api_url, headers=api_headers, json=data)
    # if response.status_code == 200:
    #     summary = response.json()
    #     return summary['summary_text']
    # else:
    #     # Handle error response
    #     print(f"API request failed with status code {response.status_code}")
    #     return None

def pdf_summary_view(request):
    if request.method == 'POST':
        pdf_file = request.FILES.get('file-input')

        # Save the uploaded PDF temporarily
        temp_path =os.path.join(settings.MEDIA_ROOT, pdf_file.name)

        with open(temp_path, 'wb') as destination:
            for chunk in pdf_file.chunks():
                destination.write(chunk)

        # Summarize the PDF
        summary_text = summarize_pdf(temp_path)

        # Clean up the temporary PDF file
        # os.remove(temp_path)
        
        # Return the summary as JSON response
        # return JsonResponse({'result': summary_text})
        return render(request,'pdf1.html',{"result": summary_text,"input":pdf_file})
    else:
        # Handle GET requests (if needed)
        return render(request, 'pdf1.html')


from transformers import pipeline

summarizer = pipeline('summarization',model='facebook/bart-large-cnn')

text=""
def output(request):
    
    data = request.POST.get('data')
    text = summarizer(data, max_length=130,min_length=60,do_sample=False)[0]['summary_text']
    request.session['text_for_speech'] = text
    request.session['summarized_text'] = text
    return render(request,'summarease.html',{'result':text,'input':data})


def texttospeech(request):
    rate = 150
    engine = pyttsx3.init()
    engine.setProperty('rate', rate)
    text = request.session.get('text_for_speech', '')
    # Use the engine to speak the given text audio
    engine.say(text)
    # Wait for the speech to finish
    engine.runAndWait()
    return render(request, 'summarease.html', {"result": text})


def language_translator(text, target_language='en'):
    translator = Translator()
    translation = translator.translate(text, dest=target_language, src='en')
    return translation.text

def translate_summary(request, target_language='hi'):
    # Ensure 'summarized_text' is present in the session
    summarized_text = request.session.get('summarized_text', '')

    if summarized_text:
        # If summarized_text is not None, proceed with translation
        translated_text = language_translator(summarized_text, target_language)

        # Set the translated text to a new session key
        request.session['translated_text'] = translated_text

        return render(request, 'summarease.html', {"result": translated_text})
    else:
        # If 'summarized_text' is not present, handle accordingly
        return render(request, 'summarease.html', {"result": "Summarized text not found in session"})


from django.shortcuts import render
from language_tool_python import LanguageTool
from django.http import JsonResponse

def grammar_checker(request):
    if request.method == 'POST':
        input_text = request.POST.get('text_to_check', '')

        # Check grammar in the given text
        tool = LanguageTool('en-US')
        matches = tool.check(input_text)

        # Apply the corrections
        corrected_text = tool.correct(input_text)

        # Return the results as JSON
        response_data = {
            'input_text': input_text,
            'corrections': [{'ruleId': match.ruleId, 'message': match.message, 'replacements': match.replacements} for match in matches],
            'corrected_text': corrected_text,
        }

        # return JsonResponse(response_data)
        return render(request,'grammar.html',{'result':corrected_text,'input':input_text})

    return render(request, 'grammar.html')



# Create your views here.
def home(request):
    return render(request,'home.html')

def login(request):

    return render(request,'login.html')
# result_text = ""
def summarease(request):
    
    return render(request, 'summarease.html')
    # return render(request, 'summarease.html')


def registration(request):
    
    return render(request, 'registration.html')
    

def forgotpassword(request):
    return render(request,'forgotpassword.html')

def logout(request):
    return render(request,'welcome.html')

def pdf1(request):
    return render(request,'pdf1.html')

def grammar(request):
    return render(request,'grammar.html')

def profile(request):
    return render(request,'profile.html')

def history(request):
    return render(request,'history.html')

project/ui/templates/grammar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Text Summarizer</title>
    <!-- Add Font Awesome link (make sure to include this in your project) -->
    <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js"></script>

    <link rel="stylesheet" href="{% static 'grammar.css' %}">
</head>
<body>
    <div id="leftPane" class="sidebar" onclick="toggleLeftPane()">
        
        <header><h3>SummarEase</h3></header>
        <ul>
            <li ><a href="{% url 'ui:summarease' %}"><i class="fas fa-file-alt icon"style="color: rgb(0, 138, 119);"></i> Text Summarizer</a></li>

            <li><a href="{% url 'ui:pdf1' %}"><i class="fas fa-file-pdf icon"style="color: blue;"></i> PdfSummarizer</a></li>
    
            <li><a href="{% url 'ui:grammar' %}"><i class="fas fa-code icon"style="color:green"></i> GrammarChecker</a></li>
            <li><a href="{% url 'ui:profile' %}" ><i class="fas fa-user icon"></i> Profile</a></li>
    
            <li></i><a href="{% url 'ui:home' %}" ><i class="fas fa-sign-out-alt icon" style="color:red"></i> Logout</a></li>
        </ul>
    </div>    
    
    <div id="mainContent" style="background-image: linear-gradient(to right, rgba(21, 187, 173, 0.638), rgba(21, 187, 173, 0.638));">
        <h2 style="text-align: center; color:rgb(255, 255, 255);">GrammarChecker and corrector</h2>
            <div class="main" style="margin-top:-1% ;">
        <div class="left" style="background-image: linear-gradient(to right, rgba(21, 187, 173, 0.638),rgba(21, 187, 173, 0.638) );">
            <form action="{% url 'ui:grammar_checker' %}" method="post" >
            {% csrf_token %}
            <textarea ondragstart="return false;" name="text_to_check" id="inputText" type="text" placeholder="Enter sentences to check and correct" rows="4" cols="30" required style="padding:10px;">{{ input }}</textarea>
            
            <button id="button" > Correct </button>
        </form>
        </div>
        <!-- <hr style="height: 90%; border: 0; border-left: 1px solid #ed0909; margin: 0 10px;"> -->
        <div class="right">
            
            {% if result %}
            <p id="output">{{ result }}</p>
            {% endif %}
        </div>
        
        
        </div>
    </div>
        
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"></script>
    <script>
        // Your JavaScript code for microphone, translation, and profile buttons
        document.getElementById('microphoneButton').addEventListener('click', function () {
            // Add your microphone functionality here
            alert('Microphone button clicked!');
        });

        document.getElementById('translateButton').addEventListener('click', function () {
            // Add your translation functionality here
            alert('Translate button clicked!');
        });

        document.getElementById('profileButton').addEventListener('click', function () {
            // Add your profile functionality here
            alert('Profile button clicked!');
        });

        function resizeTextbox(){
            const textarea = document.getElementById('userInput');
            text.style.height = 'auto';
            text.style.height=(textarea.scrollHeight + 2)+'px';

        }
        function toggleDropdown() {
            var dropdown = document.getElementById("profileDropdown");
            dropdown.style.display = (dropdown.style.display === "block") ? "none" : "block";
        }
    
        // Close the dropdown if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('#profileButton button')) {
                var dropdown = document.getElementById("profileDropdown");
                if (dropdown.style.display === "block") {
                    dropdown.style.display = "none";
                }
            }
        }
    
            function toggleLeftPane() {
              const leftPane = document.getElementById('leftPane');
              leftPane.classList.toggle('hidden');
            }
            
              
          
              function deleteOutput() {
                var outputDiv = document.getElementById('output');
                outputDiv.innerText = '';
          
                // Hide the delete button after deleting the content
                var deleteButton = document.getElementById('deletebutton');
                deleteButton.style.display = 'none';
              }
    </script>
</body>
</html>

project/ui/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="home" method="post">
     
        <button name="submit"> logout</button>

    </form>
</body>
</html>

project/ui/templates/pdf1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Text Summarizer</title>
    <!-- Add Font Awesome link (make sure to include this in your project) -->
    <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'pdf1.css' %}">
    <style>
        .sidebar header{
            text-align: center;
            background-color: #f2f2f2;
            padding: 10px;
            height: 10vh;
            color: #0a4b50;
            box-shadow: 0px 1px 10px rgba(41, 39, 39, 0.629);
        
        }
        .sidebar ul a{
            /* text-align: center; */
            /* display: block; */
            display: block;
            height: 100%;
            width: 100%;
            line-height: 85px;
            font-size: 16px;
            color: rgb(2, 60, 68);
            box-sizing: border-box;
            transition: .6s;
            padding: 1%;
            /* padding: 6%; */
            
            /* border-top: 1px solid #064a698c;
            border-bottom: 1px solid rgba(8, 63, 87, 0.612); */
        }

        .sidebar ul li {
            /* display: none; */
            padding-left: 50px;
            box-shadow: 0px 0px 9px rgba(0, 0, 0, 0.262);
            margin-left: -22%;
        }
        .sidebar li a{
            width: 120%;
            margin-left: -38px;
        }
        ul li:hover a{
            padding-left:9px ;
        }
    </style>
</head>
<body >
    <div id="leftPane" class="sidebar" onclick="toggleLeftPane()" style="background-color: rgb(255, 255, 255);">
        
        <header><h3>SummarEase</h3></header>
        <ul>
            <li ><a href="{% url 'ui:summarease' %}"><i class="fas fa-file-alt icon"style="color: rgb(0, 138, 119);"></i> Text Summarizer</a></li>
    
            <li><a href="{% url 'ui:pdf1' %}"><i class="fas fa-file-pdf icon"style="color: blue;"></i> PdfSummarizer</a></li>
    
            <li><a href="{% url 'ui:grammar' %}"><i class="fas fa-code icon"style="color:green"></i> GrammarChecker</a></li>
            <li><a href="{% url 'ui:profile' %}" ><i class="fas fa-user icon"></i> Profile</a></li>
    
            <li></i><a href="{% url 'ui:home' %}" ><i class="fas fa-sign-out-alt icon" style="color:red"></i> Logout</a></li>
        </ul>
    </div>    
    
    <div id="mainContent">
        <div class="top">
            <div class="linesContainer">
               
                <div id="control-panel">
                    <!-- Label for minimum value -->
                <!-- <p>id="minLabel"><b>PDF Summarizer</b></p> -->
                    <h3 style="color: rgb(8, 113, 113); font-size:22px; margin-left:40%"> <b>Pdf Summarizer</b></h3>

                    <div id="but" >
                        
                        <!-- <a href='{% url "ui:texttospeech" %}'><i class="fas fa-microphone larger-icon" id="microphonebutton"></i></a>
                        <a href="{% url 'ui:translate_summary' %}"><i class="fas fa-language larger-icon" id="translatebutton"></i></a> -->
                        
                        <button id="deletebutton" title="Delete" onclick="deleteOutput()" ><i class="fas fa-trash-alt larger-icon"></i></button>
                        </div>
                </div>
                
            </div>
            </div>

            <div class="main">
            <div class="left">
                
            <form id="pdfForm" action="{% url 'ui:pdf_summary_view' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="upload-container">
                    <label id="custom-upload" for="file-input">
                        <i class="fas fa-cloud-upload-alt fa-2x" style="margin-left:-10px"></i>
                    </label>
                    <!-- Actual file input (hidden) -->
                    <p style="color: darkcyan; padding-right:65%">Upload PDF</p>
                    <input type="file" id="file-input" name="file-input" accept=".pdf" onchange="displayFileName()" />
                    <p id="pdf-name" style="color: rgb(6, 84, 84); margin-left:-60%; display: none; "><b>{{ input }}</b></p>
                </div>
            
                <button id="extract-button" type="submit" onclick="submitForm()">Extract Content</button>
            </form>
            </div>

        <!-- <hr style="height: 90%; border: 0; border-left: 1px solid #ed0909; margin: 0 10px;"> -->
        <div class="right" id="rightpane">
            {% if result %}
            
            <h3>Summary:</h3>
             <p id="output">{{ result }}</p>

             {% endif %}
        </div>
        
        
        </div>
    </div>
        
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"></script>
    <script>
        function submitForm() {
            var form = document.getElementById('pdfForm');
            var formData = new FormData(form);
    
            fetch(form.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.error) {
                    console.error('Error:', data.error);
                } else {
                    // Update the content dynamically in the right pane
                    var rightPane = document.getElementById('rightPane');
                    rightPane.innerHTML = data.html_content;
    
                    // Show the delete button when there's content in the output
                    var deleteButton = document.getElementById('deletebutton');
                    deleteButton.style.display = rightPane.innerText.trim() !== '' ? 'inline-block' : 'none';
                }
            })
            .catch(error => console.error('Error:', error));
        }
            function displayFileName() {
                var input = document.getElementById('file-input');
                var fileName = input.files[0].name;
                var pdfNameElement = document.getElementById('pdf-name');
                
                // Display PDF name
                pdfNameElement.innerHTML = 'Selected PDF: ' + fileName;
                
            }

        function resizeTextbox(){
            const textarea = document.getElementById('userInput');
            text.style.height = 'auto';
            text.style.height=(textarea.scrollHeight + 2)+'px';

        }
        
              function processText() {
                var inputText = document.getElementById('inputText').value;
                var processedText = '' + inputText.toUpperCase();
                var outputDiv = document.getElementById('output');
                outputDiv.innerText = processedText;
          
                // Show the delete button when there's content in the output
                var deleteButton = document.getElementById('deletebutton');
                deleteButton.style.display = outputDiv.innerText.trim() !== '' ? 'inline-block' : 'none';
              }
          
              function deleteOutput() {
                var outputDiv = document.getElementById('output');
                outputDiv.innerText = '';
          
                // Hide the delete button after deleting the content
                var deleteButton = document.getElementById('deletebutton');
                deleteButton.style.display = 'none';
              }
            
              <!-- Add this script to your HTML file -->
             
                  
              
                  // Function to display PDF name
                  function displayFileName() {
                      var input = document.getElementById('file-input');
                      var fileName = input.files[0].name;
                      var pdfNameElement = document.getElementById('pdf-name');
              
                      // Display PDF name
                      pdfNameElement.innerHTML = 'Selected PDF: ' + fileName;
                      pdfNameElement.style.display = 'block';
                  }
             
              
    </script>
</body>
</html>

project/ui/templates/summarease.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Text Summarizer</title>
    <!-- Add Font Awesome link (make sure to include this in your project) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'summarease.css' %}">
</head>
<body>
    <div id="leftPane" class="sidebar" onclick="toggleLeftPane()">
        
        <header><h3>SummarEase</h3></header>
        <ul>
        <li ><a href="{% url 'ui:summarease' %}"><i class="fas fa-file-alt icon"style="color: rgb(0, 138, 119);"></i> Text Summarizer</a></li>

        <li><a href="{% url 'ui:pdf1' %}"><i class="fas fa-file-pdf icon"style="color: blue;"></i> PdfSummarizer</a></li>

        <li><a href="{% url 'ui:grammar' %}"><i class="fas fa-code icon"style="color:green"></i> GrammarChecker</a></li>
        <li><a href="{% url 'ui:profile' %}" ><i class="fas fa-user icon"></i> Profile</a></li>

        <li></i><a href="{% url 'ui:home' %}" ><i class="fas fa-sign-out-alt icon" style="color:red"></i> Logout</a></li>
    </ul>
    </div>            
   
</div>
    <!-- <div id="mainButton" onclick="toggleLeftPane()">Main Button</div> -->
    
    <div id="mainContent" style="background-image: linear-gradient(to right, rgba(21, 187, 173, 0.638), rgba(21, 187, 173, 0.638));">
        
        <div class="top">
            <div class="linesContainer">
                <div >
                    
                    <div id="control-panel">
                        <!-- Clickable icons using Font Awesome -->
                        <h3 style="color: rgb(8, 113, 113); font-size:22px; text-align:center"> <b>Text Summarizer </b></h3>
                        <!-- <p style="margin-left: 30px;"> Short</p>
                        <input type="range" min="0" max="100" value="50" id="line-length-slider">
                        <p>Long</p> -->
                        <div id="but" >
                        
                        <a href='{% url "ui:texttospeech" %}'><i class="fas fa-microphone larger-icon" id="microphonebutton"></i></a>
                        <a href="{% url 'ui:translate_summary' %}"><i class="fas fa-language larger-icon" id="translatebutton"></i></a>
                        
                        <button id="deletebutton" title="Delete" onclick="deleteOutput()" ><i class="fas fa-trash-alt larger-icon"></i></button>
                        </div>
                        <!-- Slider with 2 mid points -->
                    </div>
                </div>
                
            </div>
            </div>
            <div class="main" >
                <form id='summarizeForm' action="{% url 'ui:output' %}" method="post">
                    {% csrf_token %}
                    <!-- <label for="maxL">Length:</label>
                    <input type="string" name="maxL" value="30"> -->
                    <div class="left" style="background-image: linear-gradient(to right, rgba(21, 187, 173, 0.638), rgba(21, 187, 173, 0.638));">
                        <textarea   ondragstart="return false;" id="inputText" name='data' type="text" rows="4" cols="30" >{{ input }}</textarea>
                        <button id="button" onclick="processText()">Summarize</button>
                    </div>
                </form>
            
                <div class="right">
                    {% if result %}
                     <p id="output">{{ result }}</p>
                     {% endif %}
                </div>
            </div>
        
        
        </div>
    </div>
        
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"></script>
    <script>   
        document.getElementById('summarizeForm').addEventListener('submit', function () {
            var textareaValue = document.getElementById('inputText').value;
            var maxLValue = document.getElementById('maxL').value;
    
            sessionStorage.setItem('storedData', textareaValue);
            sessionStorage.setItem('storedMaxL', maxLValue);
        });     
        function closeNavbar() {
            // Close the navbar when an item is clicked
            $('.navbar-toggle').click();
        }
        // Your JavaScript code for microphone, translation, and profile buttons
        document.getElementById('microphoneButton').addEventListener('click', function () {
            // Add your microphone functionality here
            alert('Microphone button clicked!');
        });

        document.getElementById('translateButton').addEventListener('click', function () {
            // Add your translation functionality here
            alert('Translate button clicked!');
        });

        document.getElementById('profileButton').addEventListener('click', function () {
            // Add your profile functionality here
            alert('Profile button clicked!');
        });

        function resizeTextbox(){
            const textarea = document.getElementById('userInput');
            text.style.height = 'auto';
            text.style.height=(textarea.scrollHeight + 2)+'px';

        }
        function toggleDropdown() {
            var dropdown = document.getElementById("profileDropdown");
            dropdown.style.display = (dropdown.style.display === "block") ? "none" : "block";
        }
    
        // Close the dropdown if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('#profileButton button')) {
                var dropdown = document.getElementById("profileDropdown");
                if (dropdown.style.display === "block") {
                    dropdown.style.display = "none";
                }
            }
        }
    
        function processText() {
            var inputText = document.getElementById('inputText').value;
            var outputDiv = document.getElementById('output');
            //var deleteButton = document.getElementById('deletebutton');
    
            // Process the input text (You can replace this with your summarization logic)
            //var summarizedText = "Summarized: " + inputText;
    
            // Display the summarized text
            //outputDiv.innerText = summarizedText;
    
            // Show the delete button
            deleteButton.style.display = 'block';
        }
    
        function deleteOutput() {
            var outputDiv = document.getElementById('output');
            outputDiv.innerText = '';
    
            // Hide the delete button after deleting the content
            var deleteButton = document.getElementById('deletebutton');
            
        }
              
    </script>
</body>
</html>